blank_issues_enabled: true
contact_links:
  - name: Something Pink Discussions
    url: https://github.com/orgs/something-pink/discussions
    about: Post questions and feedback, or start discussions about relevant topics
  - name: Something Pink Contact
    url: https://something.pink/contact/
    about: Our corporate contact information