name: Test Godot addon with Gut
on:
  workflow_call:
    inputs:
      godot-version:
        required: true
        type: string
        default: 4.2.1-stable
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'
      - name: Setup Godot
        uses: SomethingPinkGmbH/setup-godot@v1
        with:
          version: ${{ inputs.godot-version }}
          use-dotnet: false
      - name: Workaround Godot import issue
        run: godot --headless --export-release "Linux/X11" /dev/null || true
      - name: Run tests
        run: godot -d --headless -s --path "$PWD" addons/gut/gut_cmdln.gd
